name: CI

on: [ "push" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: stable

      - name: Show CPU info
        run: lscpu

      - name: Test
        run: cargo test --workspace --verbose --all-features --no-fail-fast
